export const SUBSCRIPTION_ERROR_CODES = {
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  PRODUCT_LIMIT_REACHED: "PRODUCT_LIMIT_REACHED",
  AI_PLAN_REQUIRED: "AI_PLAN_REQUIRED",
  AI_TOKEN_LIMIT_EXCEEDED: "AI_TOKEN_LIMIT_EXCEEDED",
};

export const PLAN_SLUGS = {
  TRIAL: "trial",
  BASIC: "basic",
  PRO: "pro",
  BUSINESS: "business",
};
